# Generated by Django 5.0.6 on 2024-06-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_numer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
