# Generated by Django 5.0.6 on 2024-06-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_patient_phone_numer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
