# Generated by Django 5.0.6 on 2024-06-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_phone_numer_patient_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
